name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  repository_dispatch:
    types: [strapi_updated,database_updated]
  push:
    branches:
      - master

concurrency:
  group: prod

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ toJson(github.event.client_payload) }}
        run: echo PAYLOAD $MESSAGE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Caching
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-gatsby-build-prod-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-prod-
      - run: yarn install
      - run: yarn run build --log-pages
        env:
            CI: true
            STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
            STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
            GATSBY_DB_USER: ${{ secrets.GATSBY_DB_USER }}
            GATSBY_DB_PASS: ${{ secrets.GATSBY_DB_PASS }}
            GATSBY_DB_HOST: ${{ secrets.GATSBY_DB_HOST }}
            GATSBY_DB_PORT: ${{ secrets.GATSBY_DB_PORT }}
            GATSBY_DB_NAME: ${{ secrets.GATSBY_DB_NAME }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: estuary-marketing
          channelId: live