name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: yarn install
      - run: yarn run patch-package
      - run: yarn run build
        env:
            STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
            STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/36109138678/locations/global/workloadIdentityPools/estuary-marketing-pool/providers/estuary-marketing-provider'
          service_account: 'estuary-marketing-ci-cd@estuary-marketing.iam.gserviceaccount.com'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: "${{ github.workspace }}/public"
          destination: "estuary-marketing"
          parent: false
